// GET /api/cases/[caseId]/documents/[docId]/export
// Streams a PDF of the legal document with proper legal margins,
// ALL-CAPS section headings, and a Harvey footer on every page.

import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require("pdfkit") as typeof import("pdfkit");

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ caseId: string; docId: string }> }
) {
  const { caseId, docId } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: doc, error } = await supabase
    .from("case_documents")
    .select("id, title, content, created_at")
    .eq("id", docId)
    .eq("case_id", caseId)
    .maybeSingle();

  if (error || !doc) return NextResponse.json({ error: "Document not found" }, { status: 404 });

  const { data: caseData } = await supabase
    .from("cases")
    .select("case_number, title")
    .eq("id", caseId)
    .maybeSingle();

  // ── Strip HTML tags (editor may store HTML) ──────────────────────────────
  const plainContent = doc.content
    .replace(/<\/p>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  // ── Build PDF ─────────────────────────────────────────────────────────────
  const buffers: Buffer[] = [];
  const pdf = new PDFDocument({
    margins: { top: 72, bottom: 90, left: 90, right: 72 },
    size: "A4",
    bufferPages: true,
    info: {
      Title:   doc.title,
      Author:  "Harvey",
      Subject: caseData?.title ?? doc.title,
    },
  });

  pdf.on("data", (chunk: Buffer) => buffers.push(chunk));

  // Header bar
  const headerText = caseData
    ? `${caseData.case_number}  —  ${caseData.title}`
    : doc.title;

  pdf.font("Helvetica-Bold").fontSize(9).fillColor("#555555")
    .text(headerText, { align: "center" }).moveDown(0.4);
  pdf.moveTo(90, pdf.y).lineTo(pdf.page.width - 72, pdf.y)
    .strokeColor("#cccccc").lineWidth(0.5).stroke().moveDown(1.2);

  // Body
  const lines = plainContent.split("\n");
  for (const line of lines) {
    const t = line.trim();
    if (!t) { pdf.moveDown(0.5); continue; }

    const isHeading = t === t.toUpperCase() && t.length > 3 && !/^\d+[.)]\s/.test(t);
    if (isHeading) {
      pdf.moveDown(0.6)
        .font("Helvetica-Bold").fontSize(11).fillColor("#111111")
        .text(t, { align: "left" }).moveDown(0.4);
    } else {
      pdf.font("Helvetica").fontSize(10).fillColor("#1a1a1a")
        .text(t, { align: "justify", lineGap: 2 }).moveDown(0.25);
    }
  }

  // Footer on every page
  const range = pdf.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    pdf.switchToPage(i);
    const footerY = pdf.page.height - 50;
    pdf.font("Helvetica").fontSize(8).fillColor("#999999").text(
      `Generated by Harvey  ·  ${new Date(doc.created_at).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}  ·  Page ${i + 1} of ${range.count}`,
      90, footerY,
      { align: "center", width: pdf.page.width - 162 }
    );
  }

  pdf.end();

  const pdfBuffer = await new Promise<Buffer>((resolve) => {
    pdf.on("end", () => resolve(Buffer.concat(buffers)));
  });

  const safeName = doc.title
    .replace(/[^a-zA-Z0-9\s\-_]/g, "")
    .replace(/\s+/g, "-")
    .toLowerCase()
    .slice(0, 80);

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${safeName}.pdf"`,
      "Content-Length": String(pdfBuffer.length),
    },
  });
}
